version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB:price_comparison
      POSTGRES_USER:thesis_user
      POSTGRES_PASSWORD:thesis_pass
  ports:
    - "5432:5432"
  volumes:
    - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: